services:
  - type: web
    name: stock-manager-tipaza-1
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Tipaza0777600442@db.ndlhhihgvpuxzlitxsiq.supabase.co:5432/postgres
